apiVersion: v1
kind: Service
metadata:
  name: git-pr-mcp
  labels:
    app: git-pr-mcp
spec:
  selector:
    app: git-pr-mcp
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 8000
  type: ClusterIP
